import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { PicklistResult } from "../utils/generatePicklist";

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;

const MARGIN = 10;

const HEADER_HEIGHT = 42;
const FOOTER_HEIGHT = 10;

const COLUMN_GAP = 8;

const TABLE_WIDTH = 91;

const LEFT_X = MARGIN;
const RIGHT_X = LEFT_X + TABLE_WIDTH + COLUMN_GAP;

const MAX_ROWS_PER_COLUMN = 35;
const ITEMS_PER_PAGE = MAX_ROWS_PER_COLUMN * 2;

export const downloadPicklistPDF = (picklist: PicklistResult) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const now = new Date();

  const formattedDate = now.toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const picklistNo = `PL${Date.now()}`;

  const drawHeader = (page: number) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    // doc.text("ORDER PROCESS", 10, 12);

    doc.setFontSize(20);
    doc.text("PICKLIST", PAGE_WIDTH / 2, 15, {
      align: "center",
    });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    doc.text(`Picklist No : ${picklistNo}`, 10, 22);

    doc.text(`Generated : ${formattedDate}`, 10, 28);

    doc.text(`Total SKU : ${picklist.items.length}`, 145, 22);

    doc.text(`Total Qty : ${picklist.totalQuantity}`, 145, 28);

    doc.text(`Page : ${page}`, 145, 34);

    doc.setDrawColor(180);

    doc.line(MARGIN, HEADER_HEIGHT, PAGE_WIDTH - MARGIN, HEADER_HEIGHT);
  };

  const drawFooter = (page: number) => {
    doc.setDrawColor(180);

    doc.line(
      MARGIN,
      PAGE_HEIGHT - FOOTER_HEIGHT,
      PAGE_WIDTH - MARGIN,
      PAGE_HEIGHT - FOOTER_HEIGHT,
    );

    doc.setFontSize(9);

    // doc.text(
    //   "Generated by Order Process",
    //   MARGIN,
    //   PAGE_HEIGHT - 4,
    // );

    doc.text(
      `Warehouse Picklist | Page ${page}`,
      PAGE_WIDTH - MARGIN,
      PAGE_HEIGHT - 4,
      {
        align: "right",
      },
    );
  };

  const pages: PicklistResult["items"][] = [];

  for (let i = 0; i < picklist.items.length; i += ITEMS_PER_PAGE) {
    pages.push(picklist.items.slice(i, i + ITEMS_PER_PAGE));
  }
  pages.forEach((pageItems, pageIndex) => {
    if (pageIndex > 0) {
      doc.addPage();
    }

    drawHeader(pageIndex + 1);
    drawFooter(pageIndex + 1);

    const leftItems = pageItems.slice(0, MAX_ROWS_PER_COLUMN);

    const rightItems = pageItems.slice(MAX_ROWS_PER_COLUMN, ITEMS_PER_PAGE);

    autoTable(doc, {
      startY: HEADER_HEIGHT + 4,

      margin: {
        left: LEFT_X,
      },

      tableWidth: TABLE_WIDTH,

      head: [["SKU", "Qty"]],

      body: leftItems.map((item) => [item.sku, item.quantity.toString()]),

      styles: {
        fontSize: 9,
        cellPadding: 2,
        lineWidth: 0.1,
      },

      headStyles: {
        fillColor: [0, 0, 0],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        halign: "center",
      },

      bodyStyles: {
        halign: "center",
      },

      theme: "grid",
    });

    autoTable(doc, {
      startY: HEADER_HEIGHT + 4,

      margin: {
        left: RIGHT_X,
      },

      tableWidth: TABLE_WIDTH,

      head: [["SKU", "Qty"]],

      body: rightItems.map((item) => [item.sku, item.quantity.toString()]),

      styles: {
        fontSize: 9,
        cellPadding: 2,
        lineWidth: 0.1,
      },

      headStyles: {
        fillColor: [0, 0, 0],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        halign: "center",
      },

      bodyStyles: {
        halign: "center",
      },

      theme: "grid",
    });

    // if (pageIndex === pages.length - 1) {
    //   const finalY =
    //     Math.max(
    //       (doc as any).lastAutoTable.finalY,
    //       HEADER_HEIGHT + 4,
    //     ) + 8;

    //   autoTable(doc, {
    //     startY: finalY,

    //     margin: {
    //       left: MARGIN,
    //     },

    //     tableWidth: PAGE_WIDTH - MARGIN * 2,

    //     head: [["Summary", "Value"]],

    //     body: [
    //       [
    //         "Total SKU",
    //         picklist.items.length.toString(),
    //       ],
    //       [
    //         "Total Quantity",
    //         picklist.totalQuantity.toString(),
    //       ],
    //     ],

    //     styles: {
    //       fontSize: 10,
    //       cellPadding: 3,
    //     },

    //     headStyles: {
    //       fillColor: [232, 193, 109],
    //       textColor: [0, 0, 0],
    //       fontStyle: "bold",
    //     },

    //     theme: "grid",
    //   });
    // }
  });

  doc.save(`Picklist_${picklistNo}_${now.toISOString().slice(0, 10)}.pdf`);
};
